### ISSUE TITLE
Missing half the shadow

### ISSUE THREAD

**Issue by bojanserafimov** [YellowButShort-kys/Yellows-Lighting-Lib#1]
![image](https://user-images.githubusercontent.com/8680233/96322795-84d03900-0fe8-11eb-9c74-a0be939a54d0.png)

Looks like the bottom of the rectangle is not casting a shadow. Let me know if I'm using the library wrong :)

Code to reproduce:
```
Init()
CreateCircleLight(50, 50, 200)
CreateRectangonalBlocker(70, 80, 20, 30)
UpdateIntersection()
Draw()
```

**Comment by YellowButShort-kys** [comment]
fixed
